### ISSUE TITLE
Débugger le JS de la page Surface vue Globale

### ISSUE THREAD

**Issue by mathieulebasic** [mathieulebasic/parcel-wallonie#1]
Le potentiel nourricier a une sorte de conflit entre le js function et les transition vue mises en place

**Comment by mathieulebasic** [comment]
composant surfaceGlobale

**Comment by duduyo** [comment]
C'est quoi une sorte conflit ? comment se manifeste l'erreur ?

**Comment by mathieulebasic** [comment]
Au scroll, ya deux moments ou le potentiel nourricier apparait...
C'est du a la merde de js qui s'appelle gererVisibiliteImage qui est une fonctoin codée par Seity qui ajoute des classes dans des div en fonction du scroll...
