### ISSUE TITLE
Implémenter calcul des surfaces a mobiliser

### ISSUE THREAD

**Issue by mathieulebasic** [mathieulebasic/parcel-wallonie#10]
Besoin d'une fonction pour calcul de la surface a mobiliser qui prend en compte la part de bio et la part de pertes.

[(partbio_elevage * surface_necessaire_bio_elevage) +  ((1 -partbio_elevage) * surface_necessaire_bio_elevage)]
/ (1+30% * partpertes)

**Comment by benjaaaaaam** [comment]
tu es su @mathieulebasic du (1+30% * partpertes) ? c'est pas (1 - partpertes) ?

**Comment by mathieulebasic** [comment]
Alors yes pardon en effet, d'ailleurs j'ai rechecke mon calcul initial et c'est plutot:

[(partbio_elevage * surface_necessaire_bio_elevage) + ((1 -partbio_elevage) * surface_necessaire_bio_elevage)] *** (1 -25% * partpertes)**
