### ISSUE TITLE
Créer des watchers sur le changement de state de regime actuel pour appeler la fonction surfaceNecessaire

### ISSUE THREAD

**Issue by mathieulebasic** [mathieulebasic/parcel-wallonie#8]
le changement de régime dans le store state doit se refléter dans les données affichées. Pour cela il faut implémenter un watcher dans différents endroits ou on montre le potentiel Nourricier

**Comment by duduyo** [comment]
@mathieulebasic : tu peux me confirmer le comportement attendu / actuel ?
Actuel => quand on change dans le menu glissant de droite le regime alimentaire, aucune donnée n'est mise à jour dans la page principale
Attendu => maj de toutes les données dépendantes dans la page principale

C'est a faire pour toutes les pages Effets et Surface ?
Et est ce qu'il faut aussi le faire pour les autres paramètres ?

**Comment by mathieulebasic** [comment]
actuel et attendu: yes

Ya un distingo a faire:
- le régime change les résultats de l'API
- les autres ont un effet sur le calcul du potentiel nourricier qui est fait directement dans le front. Donc tout changement de paramètre nécessite un changement de potentiel nourricier mais seul le régime a un effet sur les calls à l'API.

J'aurais du la lier avec celle ci #3 , parce que du coup il faut changer le point d'API comme décrit dans cette issue pour faire intervenir le régime dans le calcul des surfaces necessaires.

Il faut utiliser l'ID du régime qui est dans le store.state.regime_alimentaire.id

**Comment by duduyo** [comment]
Du coup il vaut mieux que j'attaque la #3 avant ?

**Comment by mathieulebasic** [comment]
Yes
